name: LoginX
main: com.loginx.LoginX
version: 1.0.0
api-version: 1.21
author: Yukile394
commands:
  logingoster:
    description: Oyuncu girişlerini gösterir
    usage: /logingoster <oyuncu>
permissions:
  loginx.view:
    description: Oyuncu girişlerini görebilir
    default: op
