login_timeout: 60
title_interval: 4
title_colors:
  register:
    header: "&#FF69B4&lKAYIT OL"
    footer: "&#FFB6C1&oSisteme kayıt için: /register <sifre> <sifre>"
  login:
    header: "&#00FFFF&lGIRIS YAP"
    footer: "&#E0FFFF&oDevam etmek için: /login <sifre>"

# Aşağıdaki liste Konsol üzerinden /izinver kullanıldıkça otomatik dolar
trusted_players: []
