# Renkler (RGB Flop)
colors:
  primary: "#FF56A1"
  secondary: "#FFA6C1"
  success: "#FFB0E0"
  error: "#FF5555"

# Sesler
sounds:
  register_success: "ENTITY_PLAYER_LEVELUP"
  login_success: "ENTITY_EXPERIENCE_ORB_PICKUP"

# Title & ActionBar ayarları
title:
  register: "§dKayıt Ol §f/register <şifre> <şifre>"
  login: "§dGiriş Yap §f/login <şifre>"
  register_success: "§dBaşarıyla kayıt oldun!"
  login_success: "§dBaşarıyla giriş yaptın!"

# Login güvenlik
force_login: true
