name: LoginX
version: 1.0.1
main: com.loginx.LoginX
api-version: 1.21
commands:
  login:
    description: Giriş yap
    usage: /login <şifre>
  register:
    description: Kayıt ol
    usage: /register <şifre> <şifre>
  logingoster:
    description: Oyuncu login bilgilerini gösterir (Ops)
    usage: /logingoster <oyuncu>
  incele:
    description: Oyuncu bilgilerini opslar görebilir
    usage: /incele <oyuncu>
permissions:
  loginx.view:
    description: Oyuncuların loginlerini görebilir
    default: op
