name: LoginX
version: 1.0.0
main: com.loginx.LoginX
api-version: 1.21
depend: [Vault]
commands:
  register:
    description: Kayıt olma komutu
  login:
    description: Giriş yapma komutu
  skorkill:
    description: Baktığın yere En Çok Öldürenler tablosunu koyar
    permission: loginx.admin
  skorzaman:
    description: Baktığın yere En Çok Oynayanlar tablosunu koyar
    permission: loginx.admin
  skorblok:
    description: Baktığın yere En Çok Blok Kıranlar tablosunu koyar
    permission: loginx.admin
  skorsil:
    description: Haritadaki tüm aktif skor hologramlarını temizler
    permission: loginx.admin
  trap:
    description: Trap ana komutu
  trapyap:
    description: Seçili alanı Trap olarak kaydeder
    permission: loginx.admin
  trapsil:
    description: Bir trapi siler
    permission: loginx.admin
  trapbalta:
    description: Trap alanı seçmek için balta verir
    permission: loginx.admin
  trapholo:
    description: Baktığın yere Trap hologramı koyar
    permission: loginx.admin

permissions:
  loginx.admin:
    description: Skor ve Trap yönetim yetkisi
    default: op
    
